POST http://localhost:3000/user/login
Content-Type: application/json

{
   "email": "hoho@example.com",
   "password": "password"
}

###
@authToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJydXRpbGUiLCJlbWFpbCI6ImhvaG9AZXhhbXBsZS5jb20iLCJ1c2VyX2lkIjoiNWQwMzU4NTUtN2ZjYi00ZDlkLTk3NTgtYjgyYTNmMDE2MzFjIiwicG9pbnQiOjEwMH0sImlhdCI6MTczNDg2NTIxMywiZXhwIjoxNzM0ODY1ODEzfQ.5noyzo-Jw2eMN4lbHtwWHOyx3MYXdQ6d0Lehd8CztF4
GET http://localhost:3000/user/tokenTest
Authorization: Bearer {{authToken}}