POST http://localhost:3000/user/login
Content-Type: application/json

{
   "email": "hoho@example.com",
   "password": "password"
}

###
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJydXRpbGUiLCJlbWFpbCI6ImhvaG9AZXhhbXBsZS5jb20iLCJwb2ludCI6MTAwLCJ1c2VyX2lkIjoiNWQwMzU4NTUtN2ZjYi00ZDlkLTk3NTgtYjgyYTNmMDE2MzFjIn0sImlhdCI6MTczNDcwNzc0NCwiZXhwIjoxNzM0NzA4MzQ0fQ.aORk30hbd0qFuUfqwZcWMGU24hEYhk5hoEdnT3VD-QI

GET http://localhost:3000/user/tokenTest
Authorization: Bearer {{authToken}}